apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-flaskapp
  template:
    metadata:
      labels:
        app: my-flaskapp
    spec:
      containers:
        - name: my-flaskapp
          image: priyanshu1979/flask_app:latest  # Specify your Docker image here
          env:
            - name: MYSQL_HOST
              value: "mysql"          # this is your mysql's service clusture IP, Make sure to change it with yours
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 10}
        - setWeight: 60
        - pause: {duration: 10}
        - setWeight: 80
        - pause: {duration: 10}
